### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by jemshit** [Zhuinden/mvvm-aac-rxjava-retrofit-room#1] opened 2018-04-09 08:06 UTC
Hi, so you started to play with Fragment at the end i see :)

**Comment by Zhuinden** [comment] 2018-04-09 08:27
I have only 1 screen so I didn't include `simple-stack` to navigate between the N of them :stuck_out_tongue: 

Fragments are generally alright, except when they aren't. Do you by chance know how to add a fragment in such a way that [the new fragment is "below" the old fragment?](https://stackoverflow.com/a/40567197/2413303)

**Comment by jemshit** [comment] 2018-04-09 09:01
If it is for animation, only way probably is using "show() on fragmentB" and "hide() on fragmentA" i guess. Chris Banes was writing articles on fragment transitions. I only use this[ extension functions](https://github.com/jemshit/KotlinAndroidDemo/blob/master/app/src/main/kotlin/com/jemshit/kotlinandroiddemo/presentation/framework_extensions/AppCompatActivityExtensions.kt) for backstack.

**Comment by Zhuinden** [comment] 2018-04-09 09:47
Eh, replace + addToBackStack recreates the view hierarchy I think, so I'll stick with tracking the fragment state externally :D

Nice lib tho

**Comment by jemshit** [comment] 2018-04-09 09:58
When using Fragments, i try not to resist to framework :D

**Comment by Zhuinden** [comment] 2018-04-09 10:00
Oh I'm not resisting the framework either. I'm using `hide/show` and `detach/attach` and `add/remove` as intended. Along with `commitNow()` (although sometimes I default over to `commitAllowingStateLoss()` because commitNow is  a bitch with anims sometimes

**Comment by Zhuinden** [comment] 2018-04-09 15:16
Don't forget that `commitNow()` disallows `addToBackStack()` call.

**Comment by bernaferrari** [comment] 2018-04-10 06:06
Completely non related stuff, but since everywhere I go I see @Zhuinden, did you try alpha-transitions on Fragments from Support 27.1.1? I'm not sure if they FIXED, but, at least here, looks like they changed it to better!

**Comment by Zhuinden** [comment] 2018-04-10 08:36
It most likely did -- I ran into this flicker problem with 27.1.0 (and had some really strange issue with it a long time ago) so I didn't realize this is a regression that got fixed in 27.1.1.

I *was* a bit surprised that the default cross fade was acting up :smile:

**Closed as completed** 2018-04-17 11:34 UTC
